version: '2'
services:
    terminalproxy-app:
        image: terminalproxy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://terminalproxy-mysql:3306/terminalproxy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    terminalproxy-mysql:
        extends:
            file: mysql.yml
            service: terminalproxy-mysql
